os: linux
language: python
python: '3.7'
dist: xenial
compiler:
- gcc
install:
- pip install conan
- conan user
script:
- mkdir build
- cd build
- conan install .. --build=missing
- cmake .. -G "Unix Makefiles"
- cmake --build .
- make package ..