dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6 
      - conan
script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
  - conan install .
  - cmake --build .